# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MooyZQQ5KN_Ea930AgJzS-Uyvh12ugFK
"""

!apt-get update

!apt-get install -y zstd

# Install Ollama
!curl -fsSL https://ollama.com/install.sh | sh

ollama_model_id = "qwen2.5:7b"
ollama_port = 11501

!pkill -f "ollama" || true

!nohup bash -c "OLLAMA_HOST=0.0.0.0:11501 OLLAMA_ORIGINS=* ollama serve" > /content/nohup.out 2>&1 &

!sleep 5 && tail -n 50 /content/nohup.out

!curl http://127.0.0.1:11501/api/tags

!OLLAMA_HOST=http://127.0.0.1:11501 ollama pull qwen2.5:7b

!curl http://127.0.0.1:11501/api/tags

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# curl -s http://127.0.0.1:11501/api/chat \
#   -H "Content-Type: application/json" \
#   -d '{
#     "model": "qwen2.5:7b",
#     "stream": false,
#     "messages": [
#       {
#         "role": "user",
#         "content": "What is RAG? Explain briefly."
#       }
#     ]
#   }' | jq -r '.message.content'

!pip install pyngrok

from google.colab import userdata
from pyngrok import ngrok, conf

ngrok_auth = userdata.get('ngrok')

conf.get_default().auth_token = ngrok_auth

port = "11501"

public_url = ngrok.connect(port).public_url
print(public_url)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# curl -s https://precision-bagged-gem.ngrok-free.dev/api/chat -d '{
#   "model": "qwen2.5:7b",
#   "stream": false,
#   "messages": [
#     { "role": "user", "content": "What is RAG?" }
#   ]
# }' | jq -r '.message.content'

!tail -n 100 /content/nohup.out

