"""Add some updates

Revision ID: 3033253c3012
Revises: d30bfe67c939
Create Date: 2026-08-11 18:30:56.684650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3033253c3012'
down_revision: Union[str, Sequence[str], None] = 'd30bfe67c939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_schema_caches',
    sa.Column('cache_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('table_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('column_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('primary_key_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('foreign_key_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('relationship_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('schema_count >= 0 AND table_count >= 0 AND column_count >= 0 AND primary_key_count >= 0 AND foreign_key_count >= 0 AND relationship_count >= 0', name='chk_schema_cache_nonnegative_counts'),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.connection_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cache_id'),
    sa.UniqueConstraint('tenant_id', 'connection_id', name='uq_schema_cache_tenant_connection')
    )
    op.create_index('idx_schema_cache_synced_at', 'database_schema_caches', ['tenant_id', 'synced_at'], unique=False)
    op.create_index('idx_schema_cache_tenant_connection', 'database_schema_caches', ['tenant_id', 'connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_schema_cache_tenant_connection', table_name='database_schema_caches')
    op.drop_index('idx_schema_cache_synced_at', table_name='database_schema_caches')
    op.drop_table('database_schema_caches')
    # ### end Alembic commands ###
