"""Add new table

Revision ID: a80bd98545e2
Revises: 3033253c3012
Create Date: 2026-08-14 22:10:30.936730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a80bd98545e2'
down_revision: Union[str, Sequence[str], None] = '3033253c3012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_table_permissions',
    sa.Column('table_permission_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('schema_name', sa.String(length=128), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('can_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.connection_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_permission_id'),
    sa.UniqueConstraint('tenant_id', 'connection_id', 'role_id', 'schema_name', 'table_name', name='uq_db_table_permissions_scope')
    )
    op.create_index('idx_db_table_permissions_table', 'database_table_permissions', ['tenant_id', 'connection_id', 'schema_name', 'table_name'], unique=False)
    op.create_index('idx_db_table_permissions_tenant_connection_role', 'database_table_permissions', ['tenant_id', 'connection_id', 'role_id'], unique=False)
    op.create_table('database_column_permissions',
    sa.Column('column_permission_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('table_permission_id', sa.UUID(), nullable=False),
    sa.Column('column_name', sa.String(length=128), nullable=False),
    sa.Column('can_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_filter', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_aggregate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('masking_type', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(is_sensitive AND ((can_read AND masking_type <> 'none') OR (NOT can_read AND masking_type = 'none'))) OR (NOT is_sensitive AND masking_type = 'none')", name='chk_db_column_permissions_sensitive_mask'),
    sa.CheckConstraint("masking_type IN ('none', 'full', 'partial', 'email', 'phone', 'last4', 'hash', 'unmasked')", name='chk_db_column_permissions_masking'),
    sa.CheckConstraint('can_read OR can_filter OR can_aggregate', name='chk_db_column_permissions_capability'),
    sa.ForeignKeyConstraint(['table_permission_id'], ['database_table_permissions.table_permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('column_permission_id'),
    sa.UniqueConstraint('tenant_id', 'table_permission_id', 'column_name', name='uq_db_column_permissions_scope')
    )
    op.create_index('idx_db_column_permissions_table_permission', 'database_column_permissions', ['tenant_id', 'table_permission_id'], unique=False)
    op.create_table('database_row_filters',
    sa.Column('row_filter_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('table_permission_id', sa.UUID(), nullable=False),
    sa.Column('filter_name', sa.String(length=150), nullable=False),
    sa.Column('column_name', sa.String(length=128), nullable=False),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('value_source', sa.String(length=30), server_default='literal', nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("operator IN ('eq', 'ne', 'gt', 'gte', 'lt', 'lte', 'in', 'not_in', 'contains', 'starts_with', 'ends_with', 'is_null', 'not_null')", name='chk_db_row_filters_operator'),
    sa.CheckConstraint("value_source IN ('literal', 'current_user_id', 'current_tenant_id', 'current_user_email')", name='chk_db_row_filters_value_source'),
    sa.ForeignKeyConstraint(['table_permission_id'], ['database_table_permissions.table_permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_filter_id'),
    sa.UniqueConstraint('tenant_id', 'table_permission_id', 'filter_name', name='uq_db_row_filters_scope')
    )
    op.create_index('idx_db_row_filters_table_permission', 'database_row_filters', ['tenant_id', 'table_permission_id', 'enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_db_row_filters_table_permission', table_name='database_row_filters')
    op.drop_table('database_row_filters')
    op.drop_index('idx_db_column_permissions_table_permission', table_name='database_column_permissions')
    op.drop_table('database_column_permissions')
    op.drop_index('idx_db_table_permissions_tenant_connection_role', table_name='database_table_permissions')
    op.drop_index('idx_db_table_permissions_table', table_name='database_table_permissions')
    op.drop_table('database_table_permissions')
    # ### end Alembic commands ###
