"""add database connections

Revision ID: d30bfe67c939
Revises: d494a9dbcbde
Create Date: 2026-08-10 22:35:31.737462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd30bfe67c939'
down_revision: Union[str, Sequence[str], None] = 'd494a9dbcbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_connections',
    sa.Column('connection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_uuid', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('connection_name', sa.String(length=150), nullable=False),
    sa.Column('database_type', sa.String(length=30), server_default='postgresql', nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), server_default='5432', nullable=False),
    sa.Column('database_name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('ssl_mode', sa.String(length=30), server_default='prefer', nullable=False),
    sa.Column('connection_status', sa.String(length=30), server_default='untested', nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("connection_status IN ('untested', 'connected', 'failed', 'disabled')", name='chk_database_connections_status'),
    sa.CheckConstraint("database_type IN ('postgresql')", name='chk_database_connections_type'),
    sa.CheckConstraint("ssl_mode IN ('disable', 'allow', 'prefer', 'require', 'verify-ca', 'verify-full')", name='chk_database_connections_ssl_mode'),
    sa.CheckConstraint('port >= 1 AND port <= 65535', name='chk_database_connections_port'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id'),
    sa.UniqueConstraint('connection_uuid'),
    sa.UniqueConstraint('tenant_id', 'connection_name', name='uq_database_connections_tenant_name')
    )
    op.create_index('idx_database_connections_created_by', 'database_connections', ['created_by_user_id'], unique=False)
    op.create_index('idx_database_connections_status', 'database_connections', ['tenant_id', 'connection_status'], unique=False)
    op.create_index('idx_database_connections_tenant_id', 'database_connections', ['tenant_id'], unique=False)
    op.drop_index(op.f('collection_fddced424b4a4380bf2d17876c5b8bd2_1_vector_idx'), table_name='collection_fddced424b4a4380bf2d17876c5b8bd2_1', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('collection_fddced424b4a4380bf2d17876c5b8bd2_1')
    op.alter_column('chunks', 'chunk_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('chunks_chunk_project_id_fkey'), 'chunks', type_='foreignkey')
    op.drop_constraint(op.f('chunks_chunk_asset_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'projects', ['chunk_project_id'], ['project_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chunks', 'assets', ['chunk_asset_id'], ['asset_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_chunk_asset_id_fkey'), 'chunks', 'assets', ['chunk_asset_id'], ['asset_id'])
    op.create_foreign_key(op.f('chunks_chunk_project_id_fkey'), 'chunks', 'projects', ['chunk_project_id'], ['project_id'])
    op.alter_column('chunks', 'chunk_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('collection_fddced424b4a4380bf2d17876c5b8bd2_1',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_fddced424b4a4380bf2d17876c5b8bd2_1_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_fddced424b4a4380bf2d17876c5b8bd2_1_pkey')),
    sa.UniqueConstraint('chunk_id', name=op.f('collection_fddced424b4a4380bf2d17876c5b8bd2_1_chunk_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('collection_fddced424b4a4380bf2d17876c5b8bd2_1_vector_idx'), 'collection_fddced424b4a4380bf2d17876c5b8bd2_1', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index('idx_database_connections_tenant_id', table_name='database_connections')
    op.drop_index('idx_database_connections_status', table_name='database_connections')
    op.drop_index('idx_database_connections_created_by', table_name='database_connections')
    op.drop_table('database_connections')
    # ### end Alembic commands ###
