"""Add columns to Project schema

Revision ID: d494a9dbcbde
Revises: 3eb203936588
Create Date: 2026-08-05 20:20:55.730660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd494a9dbcbde'
down_revision: Union[str, Sequence[str], None] = '3eb203936588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_name', sa.String(length=150), nullable=False))
    op.add_column('projects', sa.Column('project_description', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_projects_tenant_name', 'projects', ['tenant_id', 'project_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_projects_tenant_name', 'projects', type_='unique')
    op.drop_column('projects', 'project_description')
    op.drop_column('projects', 'project_name')
    # ### end Alembic commands ###
